.PHONY: clean All

All:
	@echo "----------Building project:[ Array02_using_template - Debug ]----------"
	@cd "Array02_using_template" && "$(MAKE)" -f  "Array02_using_template.mk"
clean:
	@echo "----------Cleaning project:[ Array02_using_template - Debug ]----------"
	@cd "Array02_using_template" && "$(MAKE)" -f  "Array02_using_template.mk" clean
