.PHONY: clean All

All:
	@echo "----------Building project:[ bst01 - Debug ]----------"
	@cd "bst01" && "$(MAKE)" -f  "bst01.mk"
clean:
	@echo "----------Cleaning project:[ bst01 - Debug ]----------"
	@cd "bst01" && "$(MAKE)" -f  "bst01.mk" clean
