.PHONY: clean All

All:
	@echo "----------Building project:[ ReverseNumber - Debug ]----------"
	@cd "ReverseDigits" && "$(MAKE)" -f  "ReverseNumber.mk"
clean:
	@echo "----------Cleaning project:[ ReverseNumber - Debug ]----------"
	@cd "ReverseDigits" && "$(MAKE)" -f  "ReverseNumber.mk" clean
